Update 4-reload_gunicorn_no_downtime

diff --git a/0x1A-application_server/4-reload_gunicorn_no_downtime b/0x1A-application_server/4-reload_gunicorn_no_downtime
--- a/0x1A-application_server/4-reload_gunicorn_no_downtime
+++ b/0x1A-application_server/4-reload_gunicorn_no_downtime
@@ -1,4 +1,16 @@
 #!/usr/bin/env bash
-# Gracefully reload Gunicorn
-#pgrep gunicorn | xargs kill -HUP
-sudo systemctl reload gunicorn
+# Bash script to reload Gunicorn in a graceful way.
+
+# Get the PID of the Gunicorn process
+gunicorn_pid=$(pgrep gunicorn | head -n 1 )
+
+# check if it retunrs a PID
+if [ -z "$gunicorn_pid" ]; then
+    echo "Gunicorn process not found."
+    exit 1
+fi
+
+# Send a graceful reload signal to Gunicorn
+kill -HUP "$gunicorn_pid"
+
+echo "Graceful reload of Gunicorn completed."
